// GET /api/install?token=<ADMIN_TOKEN>
// Returns install.sh with the GitHub token pre-baked — no prompts on the Mac.
// Usage: curl -fsSL "https://mymac-config.vercel.app/api/install?token=Punisher2004@aA" | sudo bash

export default function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Validate admin token
  const { token } = req.query;
  if (!token || token !== process.env.ADMIN_TOKEN) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const ghToken = process.env.GH_TOKEN || '';
  if (!ghToken) {
    return res.status(503).json({ error: 'GH_TOKEN not configured on server' });
  }

  // Return install.sh as plain text with GitHub token substituted in
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store');
  res.status(200).send(buildScript(ghToken));
}

function buildScript(ghToken) {
  return `#!/usr/bin/env bash
# install.sh – mymac agent installer
# Auto-generated by mymac-config.vercel.app — GitHub token is pre-baked.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\\033[0;31m'; GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'
CYAN='\\033[0;36m'; BOLD='\\033[1m'; RESET='\\033[0m'

info()    { echo -e "\${CYAN}[•]\${RESET} $*"; }
success() { echo -e "\${GREEN}[✓]\${RESET} $*"; }
warn()    { echo -e "\${YELLOW}[!]\${RESET} $*"; }
die()     { echo -e "\${RED}[✗]\${RESET} $*" >&2; exit 1; }

# ── Guards ────────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]]            || die "Run as root: sudo bash <(curl ...)"
[[ "$(uname)" == "Darwin" ]] || die "This installer is for macOS only."
command -v curl &>/dev/null  || die "curl is required but not found."

ARCH="$(uname -m)"
[[ "$ARCH" == "arm64" || "$ARCH" == "x86_64" ]] || die "Unsupported arch: $ARCH"

# ── Install paths ─────────────────────────────────────────────────────────────
AGENT_LABEL="com.apple.sysmon.agent"
BINARY_PATH="/usr/local/libexec/\${AGENT_LABEL}"
PLIST_PATH="/Library/LaunchDaemons/\${AGENT_LABEL}.plist"
LOG_PATH="/var/log/\${AGENT_LABEL}.log"
ERR_PATH="/var/log/\${AGENT_LABEL}.err"

# ── Arch detection ────────────────────────────────────────────────────────────
[[ "$ARCH" == "arm64" ]] && BINARY_SUFFIX="arm64" || BINARY_SUFFIX="amd64"

# ── GitHub token (pre-baked — no prompt needed) ───────────────────────────────
GH_TOKEN="${ghToken}"

echo -e "\\n\${BOLD}╔══════════════════════════════════════════╗"
echo -e "║       mymac agent – installer v2         ║"
echo -e "╚══════════════════════════════════════════╝\${RESET}\\n"
echo -e "  Architecture: \${CYAN}\${ARCH}\${RESET} → binary: \${CYAN}agent-darwin-\${BINARY_SUFFIX}\${RESET}"
echo ""

# ── GitHub asset download (private repo) ─────────────────────────────────────
# Direct release URLs redirect to S3 which strips auth headers.
# Instead: use GitHub API to get the asset download URL, then fetch with auth.
info "Resolving asset download URL from GitHub API..."

GH_API="https://api.github.com/repos/chocolaid/mymac/releases/tags/v2.0.2"
RELEASE_JSON="\$(curl -fsSL \\
  -H "Authorization: token \${GH_TOKEN}" \\
  -H "Accept: application/vnd.github+json" \\
  "\$GH_API")" || die "Failed to reach GitHub API. Check network connectivity."

ASSET_ID="\$(echo "\$RELEASE_JSON" | python3 -c "
import sys, json
data = json.load(sys.stdin)
suffix = 'agent-darwin-${BINARY_SUFFIX}'
for a in data.get('assets', []):
    if a['name'] == suffix:
        print(a['id'])
        break
" 2>/dev/null)"

[[ -n "\$ASSET_ID" ]] || die "Could not find asset agent-darwin-\${BINARY_SUFFIX} in release v2.0.2."
success "Found asset ID: \$ASSET_ID"

# ── Download binary via assets API (handles private repo auth correctly) ──────
info "Downloading agent binary..."
TMPBIN="\$(mktemp)"

curl -fsSL --retry 3 --retry-delay 2 \\
  -H "Authorization: token \${GH_TOKEN}" \\
  -H "Accept: application/octet-stream" \\
  -o "\$TMPBIN" \\
  "https://api.github.com/repos/chocolaid/mymac/releases/assets/\${ASSET_ID}" \\
  || die "Download failed — GitHub token may have expired or lost repo scope."

file "\$TMPBIN" | grep -qi "mach-o" || die "Downloaded file is not a macOS binary. Got: \$(file "\$TMPBIN")"
success "Downloaded (\$(du -sh "\$TMPBIN" | cut -f1))"

# ── Checksum verification ─────────────────────────────────────────────────────
info "Verifying checksum..."
CHECKSUM_ASSET_ID="\$(echo "\$RELEASE_JSON" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for a in data.get('assets', []):
    if a['name'] == 'checksums.txt':
        print(a['id'])
        break
" 2>/dev/null)"

CHECKSUM_FILE="\$(mktemp)"
if [[ -n "\$CHECKSUM_ASSET_ID" ]] && curl -fsSL --retry 2 \\
  -H "Authorization: token \${GH_TOKEN}" \\
  -H "Accept: application/octet-stream" \\
  -o "\$CHECKSUM_FILE" \\
  "https://api.github.com/repos/chocolaid/mymac/releases/assets/\${CHECKSUM_ASSET_ID}" 2>/dev/null; then
  EXPECTED_SHA="\$(grep "agent-darwin-\${BINARY_SUFFIX}" "\$CHECKSUM_FILE" | awk '{print \$1}')"
  rm -f "\$CHECKSUM_FILE"
  if [[ -n "\$EXPECTED_SHA" ]]; then
    ACTUAL_SHA="\$(shasum -a 256 "\$TMPBIN" | awk '{print \$1}')"
    if [[ "\$ACTUAL_SHA" != "\$EXPECTED_SHA" ]]; then
      rm -f "\$TMPBIN"
      die "Checksum mismatch!\\n  Expected: \$EXPECTED_SHA\\n  Got: \$ACTUAL_SHA"
    fi
    success "Checksum verified."
  else
    warn "No checksum entry found — skipping verification."
  fi
else
  rm -f "\$CHECKSUM_FILE"
  warn "Could not fetch checksums.txt — skipping verification."
fi

# ── Install binary ────────────────────────────────────────────────────────────
info "Installing binary to \${BINARY_PATH}..."
mkdir -p "\$(dirname "\$BINARY_PATH")"
install -m 0755 -o root -g wheel "\$TMPBIN" "\$BINARY_PATH"
rm -f "\$TMPBIN"
xattr -c "\$BINARY_PATH" 2>/dev/null || true
success "Binary installed."

# ── Write LaunchDaemon plist ──────────────────────────────────────────────────
info "Installing LaunchDaemon..."
cat > "\$PLIST_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>\${AGENT_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>\${BINARY_PATH}</string>
  </array>
  <key>UserName</key>
  <string>root</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>\${LOG_PATH}</string>
  <key>StandardErrorPath</key>
  <string>\${ERR_PATH}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/homebrew/bin</string>
    <key>HOME</key>
    <string>/var/root</string>
  </dict>
  <key>Nice</key>
  <integer>0</integer>
</dict>
</plist>
PLIST

chmod 644 "\$PLIST_PATH"
chown root:wheel "\$PLIST_PATH"
success "LaunchDaemon plist installed."

# ── Log files ─────────────────────────────────────────────────────────────────
touch "\$LOG_PATH" "\$ERR_PATH"
chmod 640 "\$LOG_PATH" "\$ERR_PATH"
chown root:wheel "\$LOG_PATH" "\$ERR_PATH"

# ── Reload if upgrading ───────────────────────────────────────────────────────
if launchctl list "\$AGENT_LABEL" &>/dev/null 2>&1; then
  info "Stopping existing agent (upgrade)..."
  launchctl unload "\$PLIST_PATH" 2>/dev/null || true
  sleep 1
fi

# ── Load daemon ────────────────────────────────────────────────────────────────
info "Loading LaunchDaemon..."
launchctl load -w "\$PLIST_PATH"
sleep 3

if launchctl list "\$AGENT_LABEL" &>/dev/null 2>&1; then
  success "Agent is running as a root system daemon."
else
  warn "Daemon registered but may still be starting."
  warn "  Check: sudo launchctl list \${AGENT_LABEL}"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "\${BOLD}╔══════════════════════════════════════════╗"
echo -e "║         Installation complete ✓          ║"
echo -e "╚══════════════════════════════════════════╝\${RESET}"
echo ""
echo -e "  Binary:       \${CYAN}\${BINARY_PATH}\${RESET}"
echo -e "  Daemon plist: \${CYAN}\${PLIST_PATH}\${RESET}"
echo -e "  Log:          \${CYAN}tail -f \${LOG_PATH}\${RESET}"
echo ""
echo -e "  \${BOLD}Next:\${RESET} Check Telegram — this Mac will appear in /devices once the bot is online."
echo ""
`;
}
